finapp/urls.py
from django.urls import path, include
from . import views

app_name='finapp'

urlpatterns = [
    path('', views.mainview, name='main_view'),
    #path('stockdata/',views.StockInputView.as_view(), name='stock_input'),
    path('stock/',views.StockSelectionView.as_view(), name='stock_selection'),
    path('prescreen_list',views.PreScreenListView.as_view(),name='prescreen_list'),
    path('realestate/',views.RealEstateView.as_view(), name='real_estate'),
    path('contact/',views.ContactView.as_view(),name='contact'),
    path('extra/',views.ExtraView.as_view(),name='extra'),
    path('privacy/',views.privacy, name='privacy'),
    path('termsofuse/',views.termsofuse, name='termsofuse'),
    path('stock2/', views.StockSelection2View.as_view(), name='stock_selection2'), #This one is for new autocomplete feature.
    path('coming/', views.coming, name="coming"),
    path('plans/', views.plans, name='plans'),
    path('help/',views.helps,name='help'),
    path('temp-upload/',views.temp,name='temp'),
    path('performance-tab/',views.stockPerformaceTab,name='stockPerformaceTab'),
    path('visual-tab/',views.stockVisualTab,name='stockVisualTab'),
    path('backTest-tab/',views.stockBackTestTab,name='stockBackTestTab'),
    path('update-prescreenList/', views.update_prescreenList, name='update-prescreenList'),

    #======= BETA PAGE ===============
    path('betastock/',views.BetaStockSelectionView.as_view(), name='beta_stock_selection'),
    #=================END BETA PAGE =======

    ]

home/urls.py
from django.urls import path, include
from . import views

app_name="home"
urlpatterns = [


    path('', views.HomeView.as_view(), name="homepage"),
    path('register/',views.register_user, name="register"),

    path('password-reset/',views.password_reset, name="password-reset"),
    path('set-password/',views.set_password, name="set-password"),
    path('login/', views.my_login_view, name='custom_login'),

    ]

finapp/models.py
from django.db import models
from django.conf import settings
from datetime import datetime




# Create your models here.
class UserMeta(models.Model):
    user=models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    random_pass_string=models.CharField(max_length=100)

class Industry(models.Model):
    name=models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Company(models.Model):
    name=models.CharField(max_length=100)
    longticker=models.CharField(max_length=20, null=True, blank=True)
    ticker=models.CharField(max_length=15)
    industry=models.ForeignKey('Industry',related_name='industry',on_delete=models.CASCADE,default=1)

    # I've added the two boolean fields, one to check 'active' and 'inactive' company. The company that we've in our database
    # but we no longer wish to include it in our new quarter, then it's status is changed to 'inactive' or False.
    # Another is '(Free) Tier', the company that we wish to provide in free version, is labelled 'True', all other remain as 'False'
    active=models.BooleanField(default=False)
    tier=models.BooleanField(default=True)

    def __str__(self):
        return f'{self.name}:{self.ticker}'

class HousePrice(models.Model):
    ref_date = models.DateField()
    symbol=models.CharField(max_length=250)
    vector = models.CharField(max_length=250)
    coordinate = models.FloatField(null=True)
    value = models.FloatField(null=True)
    status=models.CharField(max_length=250)

    def __str__(self):
    	return self.symbol

class Contact(models.Model):
    comment = models.TextField()
    return_email=models.EmailField()
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        if len(self.comment) < 15: return self.comment
        return self.comment[:11] + " ..."

class BasicData(models.Model):
    date=models.DateField()
    rf_rate=models.FloatField(null=True)
    erp=models.FloatField(null=True)
    gdp=models.FloatField(null=True)

    def __str__(self):
        return datetime.strftime(self.date,'%m,%d,%Y')


class CompanyBeta(models.Model):
    symbol=models.CharField(max_length=10)
    beta=models.FloatField(null=True)

    def __str__(self):
        return '{}:{}'.format(self.symbol,self.beta)

class NewBeta(models.Model):
    ticker=models.ForeignKey('Company',related_name='betacompany',on_delete=models.CASCADE)
    quarter=models.CharField(max_length=6)
    beta=models.FloatField()

    def __str__(self):
        return f'{self.ticker.ticker}:{self.quarter}'


class GlobalData(models.Model):
    qend=models.DateField(null=True)
    longticker=models.CharField(max_length=25,null=True)
    revenue=models.FloatField(null=True)
    ebitda=models.FloatField(null=True)
    ecos=models.FloatField(null=True)
    ev=models.FloatField(null=True)
    mcap=models.FloatField(null=True)
    period=models.CharField(max_length=10, null=True)
    annlrev=models.FloatField(null=True)
    annlebitda=models.FloatField(null=True)
    annlecos=models.FloatField(null=True)
    pp1mcap=models.FloatField(null=True)
    pp2mcap=models.FloatField(null=True)
    pp1annlrev=models.FloatField(null=True)
    pp2annlrev=models.FloatField(null=True)
    revg6m=models.FloatField(null=True)
    revg3m=models.FloatField(null=True)
    ecosmgn=models.FloatField(null=True)
    pp1annlecos=models.FloatField(null=True)
    pp2annlecos=models.FloatField(null=True)
    conmgn3m=models.FloatField(null=True)
    conmgn6m=models.FloatField(null=True)
    mcapg3m=models.FloatField(null=True)
    mcapg6m=models.FloatField(null=True)
    exch=models.CharField(max_length=15, null=True)
    tick=models.CharField(max_length=10, null=True)
    beta=models.FloatField(null=True)
    industry=models.CharField(max_length=100, null=True)
    indrev=models.FloatField(null=True)
    indecos=models.FloatField(null=True)
    indmgm=models.FloatField(null=True)

    def __str__(self):
        return '{}-{}'.format(self.tick, self.period)


class BackTestData(models.Model):
    period=models.CharField(max_length=10)
    ticker=models.CharField(max_length=25)
    mcap=models.FloatField(null=True,blank=True)
    mcapg3m=models.FloatField(null=True,blank=True)
    mcapg6m=models.FloatField(null=True,blank=True)
    flag_val=models.CharField(max_length=20,null=True,blank=True)
    flag_revg=models.CharField(max_length=20,null=True,blank=True)
    flag_revga3y=models.CharField(max_length=20,null=True,blank=True)
    flag_igr=models.CharField(max_length=20,null=True,blank=True)
    flag_mgn=models.CharField(max_length=20,null=True,blank=True)
    flag_disc_prem=models.CharField(max_length=20, null=True,blank=True)
    flag_disc_prem_cy=models.CharField(max_length=20,null=True,blank=True)
    flag_mcap=models.CharField(max_length=20,null=True,blank=True)
    flag_spread_yoy=models.CharField(max_length=20,null=True,blank=True)
    flag_spread_3ya=models.CharField(max_length=20,null=True,blank=True)

    #flag_debt=models.CharField(max_length=20,null=True,blank=True)
    #flag_strategy=models.CharField(max_length=20,null=True,blank=True)

    class Meta:
        unique_together = ('period','ticker')

class BackTestData2(models.Model):
    period=models.CharField(max_length=10)
    ticker=models.CharField(max_length=25)

    mcap=models.FloatField(null=True,blank=True)
    mcapg3m=models.FloatField(null=True,blank=True)
    mcapg6m=models.FloatField(null=True,blank=True)
    mcapg9m=models.FloatField(null=True,blank=True)
    mcapg1y=models.FloatField(null=True,blank=True)

    #New Additions
    amcapg3m=models.FloatField(null=True,blank=True)
    amcapg6m=models.FloatField(null=True,blank=True)
    amcapg9m=models.FloatField(null=True,blank=True)
    amcapg1y=models.FloatField(null=True,blank=True)

    flag_val=models.CharField(max_length=20,null=True,blank=True)
    flag_revg=models.CharField(max_length=20,null=True,blank=True)
    flag_revg_3ya=models.CharField(max_length=20,null=True,blank=True)
    flag_igr=models.CharField(max_length=20,null=True,blank=True)
    flag_mgn=models.CharField(max_length=20,null=True,blank=True)
    flag_disc_prem=models.CharField(max_length=20, null=True,blank=True)
    flag_disc_prem_cy=models.CharField(max_length=20,null=True,blank=True)
    flag_mcap=models.CharField(max_length=20,null=True,blank=True)
    flag_spread_yoy=models.CharField(max_length=20,null=True,blank=True)
    flag_spread_3ya=models.CharField(max_length=20,null=True,blank=True)

    #New Additions
    flag_yield=models.CharField(max_length=20,null=True,blank=True)
    flag_yield_3ya=models.CharField(max_length=20,null=True,blank=True)
    flag_payout_ratio=models.CharField(max_length=20,null=True,blank=True)
    flag_payout_ratio_3ya=models.CharField(max_length=20,null=True,blank=True)
    flag_cfo_to_rev=models.CharField(max_length=20,null=True,blank=True)
    flag_cfo_to_rev_3ya=models.CharField(max_length=20,null=True,blank=True)

    pcount=models.IntegerField(default=-1)

    class Meta:
        unique_together = ('pcount','ticker')


# ========= Beta Models ==========================
class xIndustry(models.Model):
    name=models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

class xCompany(models.Model):
    name=models.CharField(max_length=100)
    longticker=models.CharField(max_length=20, null=True, blank=True)
    ticker=models.CharField(max_length=15, unique=True)
    industry=models.ForeignKey('xIndustry',related_name='xindustry',on_delete=models.CASCADE)
    active=models.BooleanField(default=False)
    tier=models.BooleanField(default=True)

    def __str__(self):
        return f'{self.name}:{self.ticker}'

class xAnnualIncomeSt(models.Model):
    fiscaldateending=models.DateField()
    reportedcurrency=models.CharField(max_length=5,null=True,blank=True)
    totalrevenue=models.FloatField(null=True,blank=True)
    ebitda=models.FloatField(null=True,blank=True)
    netincomefromcontinuingoperations=models.FloatField(null=True,blank=True)
    netincome=models.FloatField(null=True,blank=True)
    ticker=models.ForeignKey('xCompany',related_name='aicompany',on_delete=models.CASCADE)

    def __str__(self):
        return f'Income Statement for {self.ticker.ticker}::{self.fiscaldateending}'
    class Meta:
        unique_together = ('fiscaldateending','ticker')

class xAnnualBalanceSh(models.Model):
    fiscaldateending=models.DateField()
    cashandshortterminvestments=models.FloatField(null=True,blank=True)
    longtermdebt=models.FloatField(null=True,blank=True)
    ticker=models.ForeignKey('xCompany',related_name='abcompany',on_delete=models.CASCADE)

    def __str__(self):
        return f'Balance Sheet for {self.ticker.ticker}::{self.fiscaldateending}'
    class Meta:
        unique_together = ('fiscaldateending','ticker')


class xQuarterlyIncomeSt(models.Model):
    fiscaldateending=models.DateField()
    reportedcurrency=models.CharField(max_length=5,null=True,blank=True)
    totalrevenue=models.FloatField(null=True,blank=True)
    ebitda=models.FloatField(null=True,blank=True)
    netincomefromcontinuingoperations=models.FloatField(null=True,blank=True)
    netincome=models.FloatField(null=True,blank=True)
    ticker=models.ForeignKey('xCompany',related_name='qicompany',on_delete=models.CASCADE)

    def __str__(self):
        return f'Income Statement for {self.ticker.ticker}::{self.fiscaldateending}'
    class Meta:
        unique_together = ('fiscaldateending','ticker')

class xQuarterlyBalanceSh(models.Model):
    fiscaldateending=models.DateField()
    cashandshortterminvestments=models.FloatField(null=True,blank=True)
    longtermdebt=models.FloatField(null=True,blank=True)
    ticker=models.ForeignKey('xCompany',related_name='qbcompany',on_delete=models.CASCADE)

    def __str__(self):

finapp/templates/finapp/betastockselection.html
{% extends 'base.html' %}
{% load static %}
{% block main %}

<h1 class="title">Stock Analysis <strong>Beta</strong></h1>
<div class="img"><img src="{% static 'finapp/bull.jpg' %}" alt='bull picture' style="height:200px"></div>
<p class="sub-title">Please select a company below to analyze. </p>
<form method="POST">
    {% csrf_token %}
    <div class="form">
        <br>
        <select class="js-example-basic-single form-select" name="ticker" placeholder="Search Company.." style="width: 300px;">
            <option value="" disabled selected>Search Company...</option>
            {% for item in datas %}
                <option value="{{ item.ticker }}">{{item.ticker}} - {{ item.name }}</option>
            {% endfor %}
        </select>
        <div class="btn-container"><input type="submit" value="GO!" class="btn"></div>
    </div>
</form>
    <div class="description">
    <p class="item"><strong>Caveats on using results: </strong></p>
    <p><em>We are not suggesting any buy/sell but equiping you with calculation that we think can assist you in your choices.</em></p>

    <ul class="item-first">
          <li>Future may not track historical operational performance </li>
          <li>Please focus on qualitative factors to avoid value trap</li>
          <li>Search internet and SEC filings to identify any adverse update as below and make your decision:
          <ul class="item-second">
            <li>Loss of major customer/supplier</li>
            <li>Failure of pipeline product</li>
            <li>Regulatory scrutitny and recalls</li>
            <li>Management Changes and management calls</li>
            <li>Geopolitical Impact</li>
            <li>Other relevant news that may impact price</li>
          </ul>
          </li>
    </ul>
    </div>
<div class="links">
    <p>Some useful links:
    <ul>
    <li><a href="https://www.federalreserve.gov/data/nominal-yield-curve.htm" target="_blank" rel="noopener noreferrer">Fed site for data on Yield (RF), Inflation and GDP</a></li>
    <li><a href="https://pages.stern.nyu.edu/~adamodar/" target="_blank" rel="noopener noreferrer">Useful link by top professor for various inputs - ERP, Beta, Market Aggregation etc.</a></li>
    </ul></p>
</div>

<div class="overlay"></div>
<div class="spanner">
  <div class="loader"></div>
  <p>Getting data, Please wait...</p>
</div>


<style>
    .title{margin-top:100px; text-align:center;}
    .sub-title{width:70%; margin:10px auto; line-height:200%;}
    .btn-container{width: 100%;margin:10px auto;text-align:center;}
    .links{width:70%; margin:20px auto;}
    .links a:hover{text-decoration:underline;}
    .link:hover{text-decoration:underline;}
    .link{color:purple;}
    .img{text-align: center;}
    #id_ticker{font-size:1rem; padding:5px;}
    form{margin:20px auto; width:70%;border:1px solid gray;text-align: center;border-radius: 8px;box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19); }
    form label{padding:10px; display:block;font-size: 1.2rem;}
    .btn{text-align:center;padding:8px; border-radius:8px;background-color: #4B56D2;color:white; font-size:1.3rem;margin-top:15px;margin-bottom:15px;}
    .btn:hover{color:#FF8B13;}
    .description{margin:20px auto; width:70%;}
    .item-first{list-style:square;padding-left:20px; margin-top: 10px;}
    em{padding-left:10px; color:red;}
    .item-second{padding-left:20px; list-style:circle;}


    @media only screen and (max-width:768px){
        .sub-title{width:90%;}
        form{width:90%;}
        .description{width:90%;}
    }
    @media only screen and (max-width:576px){
        .sub-title{width:95%;}
        form{width:95%;}
        .description{width:95%;}
    }
</style>

<link rel="stylesheet" href="{% static 'finapp/loader.css' %}">
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
    $(document).ready(function() {
        $('.js-example-basic-single').select2({
            outerWidth:'50px'
        });
    });
</script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

<script>
  $("input[type='submit']").click(function(){
  $("div.spanner").addClass("show");
  $("div.overlay").addClass("show");
});
</script>

{% endblock %}

finapp/templates/finapp/main.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
    <div class="bg-success-subtle d-flex p-2 justify-content-around shadow tick-container">
      <div class="border border-success rounded text-center"><p class="pt-2 ps-2 pe-2 mb-0 text-success"><strong>TSX</strong></p><p class="pb-2 ps-2 pe-2 mb-0">{{tickers.3|stringformat:".2f"}}</p></div>
      <div class="border border-success rounded text-center"><p class="pt-2 ps-2 pe-2 mb-0 text-success"><strong>NASDAQ</strong></p><p class="pb-2 ps-2 pe-2 mb-0">{{tickers.4|stringformat:".2f"}}</p></div>
      <div class="border border-success rounded text-center"><p class="pt-2 ps-2 pe-2 mb-0 text-success"><strong>NYSE</strong></p><p class="pb-2 ps-2 pe-2 mb-0">{{tickers.1|stringformat:".2f"}}</p></div>
      <div class="border border-success rounded text-center"><p class="pt-2 ps-2 pe-2 mb-0 text-success"><strong>S&P500</strong></p><p class="pb-2 ps-2 pe-2 mb-0">{{tickers.2|stringformat:".2f"}}</p></div>
      <div class="border border-success rounded text-center"><p class="pt-2 ps-2 pe-2 mb-0 text-success"><strong>CAD/USD</strong></p><p class="pb-2 ps-2 pe-2 mb-0">{{tickers.0|stringformat:".3f"}}</p></div>
    </div>

    <div class="container main my-2 mx-auto">
      <h1 class="display-5 text-center">Let's Be Wealthy</h1>
      <div class="text-center"><img class="img-fluid my-3" src="{% static 'finapp/coverpic.jpg' %}" style="height:200px; text-align: center;" alt="home picture"/></div>
      <p>Our focus on value investing is different from traditional growth and value approach. We believe that valuation should be relative. With our tool, our users should be able to:
        <ul>
          <li>Compare between high multiples stock and low multiples stock</li>
          <li>Compare market's historical forecast of future operational performance</li>
          <li>Compare historical actual performance with market implied performance</li>
          <li>Able to analyze different scenarios and take calculated investment risk for alpha returns</li>
        </ul>
      </p>

      <h1 class="display-5 text-center">Our Future Goals</h1>
      <p>We want to be a place where our customer can generate analytics at high speed with least effort. We are working towards achieving:
        <ul>
          <li>Automation of Key DataInputs</li>
          <li>Automated Market and Sector Analysis for inflection points</li>
          <li>Automated categorisation and empirical studies of stocks with identical market views</li>
          <li>Automated advise on expected performance based on empirical studies</li>
        </ul>
      </p>
      <div class="bg-primary border rounded text-light">
        <div class="m-2 p-3 border border-light rounded">
          <h1 class="text-center">Get Started</h1>
          <p class="lead">We have a collection of financial data for more than 3000 publicly traded companies from the US exchanges. You can check how the stocks of different companies are performing based on recent and historical data. Click on stocks to see the performance of selected companies.</p>
          <p class="lead">Get started by creating your free account <a class="links" href="{% url 'home:register' %}?next={% url 'finapp:main_view' %}">here</a>.<span class="muted"> Also check out our <a class="links" href="{% url 'finapp:plans' %}">Pricing Plan</a> for full access.</span></p>
        </div>
      </div>

    </div>
    <style>
      @media only screen and (max-width:768px){
        .tick-container{font-size:0.65rem;}
      }
    </style>


{% endblock %}

finapp/templates/finapp/plans.html
{% extends 'base.html' %}

{% block main %}
<div class="main container text-center">
    <div class="my-4"><h1 class="display-5">Plans and Pricing</h1></div>
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
	    <div class="col-lg-4 col-md-6">
	        <div class="card mb-4 rounded-3 shadow-sm">
                <div class="card-header py-3 bg-warning"><h4 class="my-0 fw-normal">Try-Out</h4></div>
                <div class="card-body  bg-warning-subtle">
                    <h1 class="card-title pricing-card-title">$0<small class="text-body-secondary fw-light">/mo</small></h1>
                    <ul class="list-unstyled mt-3 mb-4">
                        <li>20 Tickers</li>
                        <li>No Account Required</li>
                        <li>Standard Email Support</li>
                    </ul>
                    <a class="w-100 btn btn-lg btn-outline-warning text-dark-emphasis" href="{% url 'finapp:stock_selection' %}" role="button">Get Started</a>
                </div>
            </div>
	    </div>
	    <div class="col-lg-4 col-md-6">
	        <div class="card mb-4 rounded-3 shadow-sm">
                <div class="card-header py-3 bg-primary"><h4 class="my-0 fw-normal text-light">Basic</h4></div>
                <div class="card-body bg-info-subtle">
                    <h1 class="card-title pricing-card-title">$0<small class="text-body-secondary fw-light">/mo</small></h1>
                    <ul class="list-unstyled mt-3 mb-4">
                        <li>100 Tickers</li>
                        <li>Free Account Required</li>
                        <li>Standard Email Support</li>
                    </ul>
	                <a class="w-100 btn btn-lg btn-outline-primary" href="{% url 'home:register' %}" role="button">Create a Basic Account</a>
                </div>
            </div>
	    </div>
	    <div class="col-lg-4 col-md-12">
    	    <div class="card mb-4 rounded-3 shadow-sm">
                <div class="card-header py-3 bg-success"><h4 class="my-0 fw-normal text-light">Pro</h4></div>
                <div class="card-body bg-success-subtle">
                    <h1 class="card-title pricing-card-title">$5<small class="text-body-secondary fw-light">/mo</small></h1>
                    <ul class="list-unstyled mt-3 mb-4">
                        <li>3000+ Tickers</li>
                        <li>Monthly Subscription Required</li>
                        <li>Priority Email Support</li>
                    </ul>
                    <button type="button" class="w-100 btn btn-lg btn-outline-success">Coming Soon</button>
                </div>
            </div>
	    </div>
    </div>
    <p class="lead">*Disclaimer: We are now in development phase. Plan rates and details might change without notice.</p>
</div>

{% endblock %}

finapp/templates/finapp/stockselection.html
{% extends 'base.html' %}
{% load static %}
{% block main %}

<h1 class="title">Stock Analysis</h1>
<div class="img"><img src="{% static 'finapp/bull.jpg' %}" alt='bull picture' style="height:200px"></div>
<p class="sub-title">Please select a company below to analyze. </p> <!--If you are unable to find your company in the list above, you can manually enter the data
<a class="link" href="#">here</a></p> -->
<form method="POST">
    {% csrf_token %}
    <div class="form">
        <!-- {{tick_form.as_p}} -->
        <!-- <input type="text" list="tickers" name="ticker" id="ticker" placeholder="Search Company.." class="form-control" style="width: 300px; margin: auto;"> -->
        <!-- <datalist id="tickers">
            {% for results in tick_form %}
            <option value="{{results.ticker}}">{{results.name}} --- {{results.ticker}}</option>
            {% endfor %}
        </datalist> -->
        <br>
        <select class="js-example-basic-single form-select" name="ticker" placeholder="Search Company.." style="width: 300px;">
            <option value="" disabled selected>Search Company...</option>
            {% for item in datas %}
                <option value="{{ item.ticker }}">{{item.ticker}} - {{ item.name }}</option>
            {% endfor %}
        </select>
        <div class="btn-container"><input type="submit" value="GO!" class="btn"></div>
    </div>
</form>
    <div class="description">
    <p class="item"><strong>Caveats on using results: </strong></p>
    <p><em>We are not suggesting any buy/sell but equiping you with calculation that we think can assist you in your choices.</em></p>

    <ul class="item-first">
          <li>Future may not track historical operational performance </li>
          <li>Please focus on qualitative factors to avoid value trap</li>
          <li>Search internet and SEC filings to identify any adverse update as below and make your decision:
          <ul class="item-second">
            <li>Loss of major customer/supplier</li>
            <li>Failure of pipeline product</li>
            <li>Regulatory scrutitny and recalls</li>
            <li>Management Changes and management calls</li>
            <li>Geopolitical Impact</li>
            <li>Other relevant news that may impact price</li>
          </ul>
          </li>
    </ul>
    </div>
<div class="links">
    <p>Some useful links:
    <ul>
    <li><a href="https://www.federalreserve.gov/data/nominal-yield-curve.htm" target="_blank" rel="noopener noreferrer">Fed site for data on Yield (RF), Inflation and GDP</a></li>
    <li><a href="https://pages.stern.nyu.edu/~adamodar/" target="_blank" rel="noopener noreferrer">Useful link by top professor for various inputs - ERP, Beta, Market Aggregation etc.</a></li>
    </ul></p>
</div>

<div class="overlay"></div>
<div class="spanner">
  <div class="loader"></div>
  <p>Getting data, Please wait...</p>
</div>


<style>
    .title{margin-top:100px; text-align:center;}
    .sub-title{width:70%; margin:10px auto; line-height:200%;}
    .btn-container{width: 100%;margin:10px auto;text-align:center;}
    .links{width:70%; margin:20px auto;}
    .links a:hover{text-decoration:underline;}
    .link:hover{text-decoration:underline;}
    .link{color:purple;}
    .img{text-align: center;}
    #id_ticker{font-size:1rem; padding:5px;}
    form{margin:20px auto; width:70%;border:1px solid gray;text-align: center;border-radius: 8px;box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19); }
    form label{padding:10px; display:block;font-size: 1.2rem;}
    .btn{text-align:center;padding:8px; border-radius:8px;background-color: #4B56D2;color:white; font-size:1.3rem;margin-top:15px;margin-bottom:15px;}
    .btn:hover{color:#FF8B13;}
    .description{margin:20px auto; width:70%;}
    .item-first{list-style:square;padding-left:20px; margin-top: 10px;}
    em{padding-left:10px; color:red;}
    .item-second{padding-left:20px; list-style:circle;}


    @media only screen and (max-width:768px){
        .sub-title{width:90%;}
        form{width:90%;}
        .description{width:90%;}
    }
    @media only screen and (max-width:576px){
        .sub-title{width:95%;}
        form{width:95%;}
        .description{width:95%;}
    }
</style>

<link rel="stylesheet" href="{% static 'finapp/loader.css' %}">
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
    $(document).ready(function() {
        $('.js-example-basic-single').select2({
            outerWidth:'50px'
        });
    });
</script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

<script>
  $("input[type='submit']").click(function(){
  $("div.spanner").addClass("show");
  $("div.overlay").addClass("show");
});
</script>

{% endblock %}