finapp/urls.py
from django.urls import path, include
from . import views

app_name='finapp'

urlpatterns = [
    path('', views.mainview, name='main_view'),
    #path('stockdata/',views.StockInputView.as_view(), name='stock_input'),
    path('stock/',views.StockSelectionView.as_view(), name='stock_selection'),
    path('prescreen_list',views.PreScreenListView.as_view(),name='prescreen_list'),
    path('realestate/',views.RealEstateView.as_view(), name='real_estate'),
    path('contact/',views.ContactView.as_view(),name='contact'),
    path('extra/',views.ExtraView.as_view(),name='extra'),
    path('privacy/',views.privacy, name='privacy'),
    path('termsofuse/',views.termsofuse, name='termsofuse'),
    path('stock2/', views.StockSelection2View.as_view(), name='stock_selection2'), #This one is for new autocomplete feature.
    path('coming/', views.coming, name="coming"),
    path('plans/', views.plans, name='plans'),
    path('help/',views.helps,name='help'),
    path('temp-upload/',views.temp,name='temp'),
    path('performance-tab/',views.stockPerformaceTab,name='stockPerformaceTab'),
    path('visual-tab/',views.stockVisualTab,name='stockVisualTab'),
    path('backTest-tab/',views.stockBackTestTab,name='stockBackTestTab'),
    path('update-prescreenList/', views.update_prescreenList, name='update-prescreenList'),

    #======= BETA PAGE ===============
    path('betastock/',views.BetaStockSelectionView.as_view(), name='beta_stock_selection'),
    #=================END BETA PAGE =======

    ]

home/urls.py
from django.urls import path, include
from . import views

app_name="home"
urlpatterns = [


    path('', views.HomeView.as_view(), name="homepage"),
    path('register/',views.register_user, name="register"),

    path('password-reset/',views.password_reset, name="password-reset"),
    path('set-password/',views.set_password, name="set-password"),
    path('login/', views.my_login_view, name='custom_login'),

    ]

finapp/views.py
from django.shortcuts import render, redirect
from django.views import View
from .forms import CompanyForm, PostCompanyForm, LocationForm, TickerInput, ContactForm
from .newscript import main_calculation
from django.contrib.auth.mixins import LoginRequiredMixin
from .backscript import backtest
from .models import HousePrice, BasicData, CompanyBeta, Company, UserTicker, TickerPrescreenData
from django.http import JsonResponse

from .alphascript import alpha_calc

import pandas as pd
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import io, base64
from matplotlib.ticker import LinearLocator
import seaborn as sns
import datetime as dt
sns.set_theme(style='darkgrid')
import yfinance as yf

from dal import autocomplete

import traceback, sys
from finapp.scripts import company_upload, industry_upload, upload_global, upload_basic_data, data_upload2, update_beta
from django.http import HttpResponse
import json
#import yahooquery as yq

#===========================================================
# Landing Page View
#===========================================================
def mainview(request):
    try:
        tickers=yf.download(tickers=['^IXIC','^GSPTSE','CADUSD=X','^DJI','^GSPC'], period='1d')['Close'].values.flatten().tolist()
    except:
        tickers=['Data Unavailable'] * 4

    context = {'tickers':tickers, 'is_auth':'user.is_authenticated'}
    return render(request, 'finapp/main.html', context)

#===========================================================
# Privacy Policy Page View
#===========================================================
def privacy(request):
    context = {}
    return render(request, 'finapp/privacy.html', context)

#===========================================================
# Terms of Use Page View
#===========================================================
def termsofuse(request):
    context = {}
    return render(request, 'finapp/termsofuse.html', context)

#============================================================
# Plans and Pricing View
#============================================================
def plans(request):
    context={}
    return render(request, 'finapp/plans.html',context)

#============================================================
# Help View
#============================================================
def helps(request):
    context={}
    return render(request, 'finapp/help.html',context)

#============================================================
# Coming Soon View
#============================================================
def coming(request):
    context={}
    return render(request, 'finapp/comingsoon.html',context)


def update_prescreenList(request):
     data = request.GET.get('checked')
     ticker = request.GET.get('ticker')

     if data == "true":
         user = request.user  
         result = alpha_calc(ticker, 1)
         data_dict = {
                    'imp_growth_TTM': result[0],
                    'rev_growth_TTM': result[1],
                    'rev_growth_3y': result[2],
                    'ecos_margin_TTM': result[3],
                    'ecos_margin_3y': result[4],
                    'ebitda_margin_TTM': result[5],
                    'ebitda_margin_3y': result[6],
                    'industry': result[7],
                    'sharpe_ratio_5':result[8][0],
                    'variance_5':result[8][1],
                    'ttm_date':result[9]
            }
            # obj = TickerPrescreenData(ticker=ticker,fetched_data=data_dict)
            # obj.save()
         obj, created = TickerPrescreenData.objects.update_or_create(
                                                        ticker=ticker,
                                                        defaults={'fetched_data': data_dict}
                                                        )
         

         new_row = UserTicker(ticker=ticker,user=user)
         new_row.save()
        
    
     if data == "false":
        obj =  UserTicker.objects.filter(user_id=request.user,ticker=ticker).first()
        if obj:
         obj.delete()

     return JsonResponse({
            'status': 'success',
            'checked': data,
        })

#==================================================================
# Stock Selection View with company selection.
#==================================================================
class StockSelectionView(LoginRequiredMixin, View):
    """
    Creating a new version of Stock Input View which has only company selection button and will show the calculation by
    downloading data from yahoo finance without showing any data.
    """
    def get(self, request):
        # tick_form=Company.objects.all() #New Code
        # context={'tick_form':tick_form}
        if request.user.is_staff:
            datas=Company.objects.all()
        else:
            datas = Company.objects.filter(tier=1)
        form = CompanyForm()
        return render(request, 'finapp/stockselection.html', {'form':form,'datas':datas})

    def post(self,request):
        # tick_form=TickerInput(request.POST)
            tick_form=PostCompanyForm(request.POST)
            if tick_form.is_valid() is not True:
                context={'tick_form':tick_form}
                return render(request, 'finapp/stockselection.html', context)
            ticker=tick_form.cleaned_data['ticker']
            print(ticker)
            # This is backtest data

            #-----THIS IS FOR DEVELOPMENT ONLY CODE--------

            #buckets, matches, summary_details, chart1, qtr_details = backtest(ticker)

            #------END OF DEVELOPMENT ONLY CODE-------------

            #-----THIS IS FOR PRODUCTION ONLY CODE--------
            """
            try:
                buckets, matches, summary_details, chart1, qtr_details = backtest(ticker)
            except Exception as ex:
                errormsg = traceback.format_exc()
                print(ex)
                context={'traceback':errormsg, 'source':'Back Testing'}
                return render(request, 'finapp/errortemp.html',context)
            """
            #------END OF PRODUCTION ONLY CODE-------------


            #Getting Alpha Calculations---------
            comparative_table,tick_detail, ynews, new_result,plot1, plot2, waterfallchart,eer_table=alpha_calc(ticker)
            '''
            try:
                comparative_table,tick_detail, new_result,plot1, plot2, waterfallchart=alpha_calc(ticker)
            except Exception as ex:
                errormsg = traceback.format_exc()
                context={'traceback':errormsg, 'source':'Main Calculation'}
                return render(request, 'finapp/errortemp.html',context)
            '''
            #context={'comparative':comparative_table, 'is_data':True, 'tick_detail':tick_detail, 'new_result':new_result,'plot1':plot1,'plot2':plot2,'waterfallchart':waterfallchart, 'backout':buckets,
            #        'matches':matches, 'summary_details':summary_details, 'chart1':chart1, 'qtr_details':qtr_details}
            #print("tick_detail",tick_detail)
            request.session['comparative_table']=comparative_table
            request.session['new_result']=new_result
            request.session['eer_table']=eer_table
            request.session['plot1']=plot1
            request.session['waterfallchart']=waterfallchart

            # check if ticker has been in prescreen list by user
            isPrescreenExist = UserTicker.objects.filter(user=request.user,ticker=ticker).exists()

            context = {'tick_detail':tick_detail,'ticker':ticker, 'ynews':ynews,'isPrescreenExist':isPrescreenExist}
            return render(request, 'finapp/stockresult2.html',context)


class PreScreenListView(LoginRequiredMixin, View):
  def get(self, request):
       
    #  tickers = ['AMZN', 'WMT', 'COST']
    #  data_list = []

    #  for ticker in tickers:
    #    result = alpha_calc(ticker, 1)
    #    data_list.append({'ticker': ticker, 'data': result})

    user_ticker_records = {ut.ticker: ut for ut in UserTicker.objects.filter(user=request.user)}

    user_ticker = UserTicker.objects.filter(user=request.user).values_list('ticker', flat=True)
    ticker_data = TickerPrescreenData.objects.filter(ticker__in=user_ticker)

    data = []
    for prescreen in ticker_data:
        ticker = prescreen.ticker
        date_added = user_ticker_records[ticker].date_added if ticker in user_ticker_records else None
        data.append({'ticker':ticker,'date_added':date_added,'fetched_data':prescreen.fetched_data})
        print(data)

    context = {'data_list': data}

    return render(request, 'finapp/prescreenlist.html', context)
         

def stockPerformaceTab(request):
     comparative = request.session.get('comparative_table')
     new_result = request.session.get('new_result')
     ainc_data = request.session.get('ainc_data')
     abal_data = request.session.get('abal_data')
     qinc_data = request.session.get('qinc_data')
     qbal_data = request.session.get('qbal_data')
     eer = request.session.get('eer_table')
     html_content = render(request, 'finapp/tabs/performance.html',{'comparative':comparative,'new_result':new_result,'ainc_data':ainc_data,'abal_data':abal_data,'qinc_data':qinc_data,'qbal_data':qbal_data,'is_data':True,'eer':eer})

     return HttpResponse(html_content, content_type='text/html')

def stockVisualTab(request):
     plot1 = request.session.get('plot1')
     waterfallchart = request.session.get('waterfallchart')
     html_content = render(request, 'finapp/tabs/visualization.html',{'plot1':plot1,'waterfallchart':waterfallchart})
     return HttpResponse(html_content, content_type='text/html')

def stockBackTestTab(request):
     ticker = request.GET.get('ticker')
     print(ticker)
     buckets, matches, summary_details, chart1, qtr_details = backtest(ticker)

finapp/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="My Amazing Stocks is a platform for delivering value based investing ideas based on data,
        historical and present, by creating statistical, machine learning and AI based modelling.">
  <title>My Amazing Stocks</title>
  <link rel="stylesheet" href="{% static 'finapp/custom.css' %}">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Rajdhani|Acme|Murecho|WindSong">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
  <link rel="shortcut icon" type="image/ico" href="{% static 'favicon.ico' %}">
  <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <link rel="stylesheet" href="{% static 'finapp/loader.css' %}">

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-table@1.25.0/dist/bootstrap-table.min.css">


  <style>
    body {
      display: flex;
      min-height: 100vh;
      flex-direction: column;
    }

    .main {
      flex: 1;
    }

    .links {
      text-decoration: none;
      color: inherit;
    }

    .links:hover {
      text-decoration: underline;
    }
  </style>

</head>

<body>
  <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'finapp:main_view' %}"
        style="font-family: WindSong, sans-serif; font-size: 1.5rem;">My Amazing Stocks</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent"
        style="font-family:Rajdhani,sans-serif; font-size: 1.5rem;">
        <ul class="navbar-nav ms-auto">
          {% if request.user.is_staff %}
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'finapp:beta_stock_selection' %}"><i
                class="bi bi-wrench-adjustable-circle"></i> BETA</a>
          </li>
          {% endif %}

          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'finapp:stock_selection' %}"><i
                class="bi bi-graph-up-arrow"></i> STOCKS</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'finapp:prescreen_list' %}"><i
                class="bi bi-graph-up-arrow"></i> Prescreen List</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'finapp:real_estate' %}"><i class="bi bi-houses"></i> REAL ESTATE</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="bi bi-person-circle"></i> ACCOUNT
            </a>
            <ul class="dropdown-menu">
              {% if user.is_authenticated %}
              <li><a class="dropdown-item" href="#">SETTINGS</a></li>
              <li><a class="dropdown-item" href="{% url 'logout' %}?next={% url 'finapp:main_view' %}">SIGN OUT</a></li>
              {% else %}
              <li><a class="dropdown-item" href="{% url 'login' %}?next={% url 'finapp:main_view' %}">SIGN IN</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><a class="dropdown-item"
                  href="{% url 'home:register' %}?next={% url 'finapp:main_view' %}">REGISTER</a></li>
              {% endif %}
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'finapp:help' %}"><i class="bi bi-question-circle"></i> HELP</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  {% block main %}
  {% endblock %}

  <div class="container-fluid bg-dark text-light py-3 d-flex flex-column" id="back"
    style="font-family:Rajdhani,sans-serif ;">
    <div class="d-flex justify-content-between">
      <div>
        <div>Follow Us At</div>
        <div><i class="bi-facebook"></i> | <i class="bi-twitter"></i> | <i class="bi-instagram"></i></div>
      </div>
      <div><a href="{% url 'finapp:privacy' %}" class="links">Privacy</a><span class="ps-3 pe-3">|</span><a
          href="{% url 'finapp:termsofuse' %}" class="links">Terms of Use</a><span class="ps-3 pe-3">|</span><a
          href="{% url 'finapp:contact' %}" class="links">Contact</a></div>
    </div>
    <div class="text-center pt-2">Copyright 2025, My Amazing Stocks Teams</div>
  </div>

 <script src="https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>
   
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap-table@1.25.0/dist/bootstrap-table.min.js"></script>
</body>

</html>